[tool.black]
line-length = 88
target-version = ['py37']
include = '\.pyi?$'
exclude = '''

(
  /(
      \.eggs         # exclude a few common directories in the
    | \.git          # root of the project
    | \.hg
    | \.mypy_cache
    | \.tox
    | \.venv
    | _build
    | buck-out
    | build
    | dist
  )/
  | cogs/listeners/guild.py
  | cogs/listeners/images.py
  | cogs/listeners/messages.py
  | cogs/listeners/users.py
  | cogs/maincommands/guildcommands.py
  | cogs/maincommands/info.py
  | cogs/maincommands/modcommands.py
  | cogs/maincommands/raid.py
  | cogs/maincommands/report.py
  | cogs/maincommands/tags.py
  | cogs/consts.py
)
'''